### ISSUE TITLE
Error when trying to solve from visualizer

### ISSUE THREAD

**Issue by iliakur** [potassco/asprilo#12]
I have a strong suspicion that this is related to [an issue I posted earlier](https://github.com/asprilo/asprilo.github.io/issues/1), but since there hasn't been any response there and I'm not completely sure my guess is correct, I'm opening a separate ticket here.

I'm running clingo 5.2.0, because I can't find any mention of version 5.3...
Whenever I try to solve an instance from the visualizer, I get the following error.
```
Connection with: ('127.0.0.1', 44162)
ground: 0
solve: 0
Traceback (most recent call last):
  File "/home/quickbeam/code/asprilo/visualizer/scripts/solver_inc.py", line 43, in <module>
    solver.run()
  File "/home/quickbeam/code/asprilo/visualizer/scripts/network.py", line 98, in run
    if self.receive(1.0) is '':
  File "/home/quickbeam/code/asprilo/visualizer/scripts/network.py", line 56, in receive
    self.on_raw_data(self._raw_data)
  File "/home/quickbeam/code/asprilo/visualizer/scripts/network.py", line 123, in on_raw_data
    self.on_data(self._data)
  File "/home/quickbeam/code/asprilo/visualizer/scripts/solver.py", line 25, in on_data
    if self.solve() < 0:
  File "/home/quickbeam/code/asprilo/visualizer/scripts/solver_inc.py", line 25, in solve
    solve_future = self._control.solve_async(self.on_model)
AttributeError: 'clingo.Control' object has no attribute 'solve_async'
close solver
Close connection to solver
```

**Comment by Thomas-Otto** [comment]
@Copper-Head 
The current version from the master branch only supports clingo 5.0. Try the latest version from the develop branch. It supports clingo 5.2.

**Comment by iliakur** [comment]
Ah, I had to pull in some changes into my local copy of develop and now it seems to work. Do you mind keeping this open until wednesday when I can test this more thoroughly? If no error appears, I'll just close it myself.
