### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by gpiffaretti** [potassco/asprilo#33]
I'm getting the following error, looks like it might be related to this:
https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows

I didn't find anything about OS support, is this supposed to work on Windows?
Here's the error:

`(aspriloEnv) PS C:\Users\gnp89> gen -x 10 -y 20 -X 2 -Y 1 -s 20 -C --random
Traceback (most recent call last):
  File "C:\Users\gnp89\.conda\envs\aspriloEnv\Scripts\gen-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\gnp89\.conda\envs\aspriloEnv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\__main__.py", line 11, in main
  File "C:\Users\gnp89\.conda\envs\aspriloEnv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 74, in run
  File "C:\Users\gnp89\.conda\envs\aspriloEnv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 84, in _run_once
  File "C:\Users\gnp89\.conda\envs\aspriloEnv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 227, in _gen_basic
  File "C:\Users\gnp89\.conda\envs\aspriloEnv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\generator.py", line 138, in generate
AttributeError: module 'signal' has no attribute 'SIGALRM'`

**Comment by pobermei** [comment]
You are correct. The generator uses POSIX singal handling which is, unfortunately, not supported by Windows. There are no short-term plans to change this dependency.
